apiVersion: devices.kubeedge.io/v1alpha2
kind: DeviceModel
metadata:
  name: counter-model
  namespace: default
spec:
  properties:
    - name: status
      description: "Trạng thái BẬT hoặc TẮT của bộ đếm"
      type:
        string:
          accessMode: ReadWrite
